---
title: "Proyecto Final"
author: "Michelle Audirac"
date: "18 Diciembre, 2017"
output:
  pdf_document: default
  html_document: default
---

```{r setup, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

instalar <- function(paquete) {

    if (!require(paquete,character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)) {
        install.packages(as.character(paquete), dependecies = TRUE, repos = "http://cran.us.r-project.org")
        library(paquete, character.only = TRUE, quietly = TRUE, warn.conflicts = FALSE)
    }
}

paquetes <- c('tidyr', 'dplyr', 'ggplot2')

#paquetes <- c('lubridate', 'magrittr', 'ggvis', 'dplyr', 'tidyr', 'readr', 'rvest', 
#              , 'stringr', 'ggthemes', 'googleVis', 'shiny', 'tibble', 'vcd', 'vcdExtra', 
#              'GGally', 'readODS', 'readxl', "RSQLite", 'extracat', 'gridExtra', 'outliers')

lapply(paquetes, instalar)

```

```{r}
train <- read.csv('./data/train.csv')
class(train)
str(train)
```

```{r}
train$TripType <- as.factor(train$TripType)
train$VisitNumber <- as.factor(train$VisitNumber)
train$Upc <- as.factor(train$Upc)
train$FinelineNumber <- as.factor(train$FinelineNumber)
```

```{r}
train %>% 
  select(TripType, VisitNumber)
```


```{r}
levels(train$TripType)

ggplot(train, aes(TripType, fill = TripType)) +
  geom_bar(colour = 'grey', alpha = 0.7) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "numero de trip types", x = "TripType", y = "count") +
  coord_flip()
```

```{r}
levels(train$Weekday)

ggplot(train, aes(Weekday, fill = Weekday)) +
  geom_bar(colour = 'grey', alpha = 0.7) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  labs(title = "numero articul", x = "Weekday", y = "count") +
  coord_flip()
```

```{r}
#'############################################################
#' explore_numeric
#' 
#'####################
#' The explore_numeric function creates a series of plots to
#' explore numeric variables.
#' 
#'########################################
explore_numeric <- function(
  #' numeric array
  x 
){
  print(summary(x))
  par(mar = c(2.5, 2.5, 2.5, .5), 
      mfrow = c(3,2))
  hist(x)
  boxplot(x)
  stripchart(x, method = "jitter")
  #plot(density(x, na.rm = TRUE))
  rug(x)
  qqnorm(x)
  qqnorm(log(x), main = "Log-Normal Q-Q Plot")
  par(mar = c(5.1, 4.1, 4.1, 2.1), 
      mfrow = c(1,1))
}
```

```{r}
#'############################################################
#' explore_factor
#' 
#'####################
#' The explore_factor function creates a series of plots to
#' explore factor variables.
#' 
#'########################################
explore_factor <- function(
  #' factor array
  x 
){
  print(summary(x))
  print("Level Legends ")
  print(paste(1:length(levels(x)), "-", levels(x)))
  levels(x) <- 1:length(levels(x))
  plot(x)
}
```

```{r}
#'############################################################
#' explore_univariate
#' 
#'####################
#'
#'########################################

explore_univariate <- function(df) {
  for(c in 1:ncol(df)) {
    if(is.numeric(df[,c])) {
      print(paste("explore_numeric:", colnames(df)[c]))
      explore_numeric(df[,c])
    }
    if(is.factor(df[,c])) {
      print(paste("explore_factor:", colnames(df)[c]))
      explore_factor(df[,c])
    }
  }
}
```

```{r}
explore_univariate(test)
```


<!-- # Ejercicio 1 -->

<!-- El propósito de este ejercicio es proveer scripts para la carga, preparación y limpieza de datos de un data set en `imports.csv` en una manera reproducible. -->

<!-- El folder `/mi_examen` contiene los archivos listados abajo: -->

<!--  * `metadata.R` -->
<!--  * `utils.R` -->
<!--  * `00-load.R` -->
<!--  * `01-prepare.R` -->
<!--  * `02-clean.R` -->
<!--  * `imports.R` -->

<!-- Un folder `/mi_examen/data` es utilizado para guardar la data fuente y la data procesada: -->

<!-- * `imports-85.csv` -->
<!-- * `imports-85.names` -->
<!-- * `imports.rds` -->

<!-- La descripción de `imports-85.csv` se encuentra en `imports-85.names`. -->

<!-- ```{r engine='bash', comment=''} -->
<!-- cat ./data/imports-85.names -->
<!-- ``` -->

<!-- ### `metadata.R` y `utils.R` -->

<!-- * El script `metadata.R` contiene los nombres de las columnas de nuestros datos. -->

<!-- ```{r engine='bash', comment=''} -->
<!-- cat metadata.R -->
<!-- ``` -->

<!-- ```{r} -->
<!-- source('metadata.R') -->
<!-- imports_colnames -->
<!-- ``` -->

<!-- * El script `utils.R` contiene las funciones requeridas para la carga, preparación y limpieza de datos de forma reproducible. Adicionalmente contiene funciones que se utilizarán más adelante para lograr el análisis exploratorio de datos. -->

<!-- ```{r engine='bash', comment=''} -->
<!-- cat utils.R -->
<!-- ``` -->


<!-- ```{r} -->
<!-- source('utils.R') -->
<!-- ls() -->
<!-- ``` -->

<!-- ### Carga de datos -->

<!-- Cargamos los datos (utilizo `read.csv` en lugar de `read_csv`. Esto porque 'read_csv` hace un parsing y corrige errores automaticamente) y vemos los tipos de datos. -->

<!-- ```{r engine='bash', comment=''} -->
<!-- cat 00-load.R -->
<!-- ``` -->

<!-- ```{r} -->
<!-- source('00-load.R') -->
<!-- glimpse(imports_data) -->
<!-- ``` -->

<!-- ### Preparación de datos -->

<!-- Preparamos los datos (en este caso la preparación de columnas solo requería incluir los nombres de la columnas) y vemos el resultado. -->

<!-- ```{r engine='bash', comment=''} -->
<!-- cat 01-prepare.R -->
<!-- ``` -->

<!-- ```{r} -->
<!-- source('01-prepare.R') -->
<!-- str(imports_data) -->
<!-- ``` -->

<!-- ### Limpieza de datos -->

<!-- Veamos algunos problemas en la data. -->

<!-- La función `read_csv` de la paquetería `readr` hace un parsing que "adivina" los tipos de datos y elimina errores. Adicionalmente `problems` captura algunos errores en la data y muestra un resumen de dichos problemas. Por eso utilizaremos las funcionalidades de la paquetería `readr` para encontrar errores en la data. -->

<!-- ```{r} -->
<!-- imports_data2<- read_csv('./data/imports-85.csv',  -->
<!--                          col_names = FALSE,  -->
<!--                          na = '?',  -->
<!--                          col_types = cols(X10 = col_double(), X14 = col_double())) -->
<!-- problems(imports_data2) -->
<!-- ``` -->

<!-- Veamos con más detalle los errores -->

<!-- ```{r} -->
<!-- renglones_problema <- unique(problems(imports_data2)$row) -->
<!-- renglones_problema -->
<!-- ``` -->

<!-- ```{r} -->
<!-- columnas_problema <- unique(problems(imports_data2)$col) -->
<!-- columnas_problema <- gsub('X', '', columnas_problema) -->
<!-- columnas_problema <- as.numeric(columnas_problema[!is.na(columnas_problema)]) -->
<!-- columnas_problema -->
<!-- ``` -->

<!-- ```{r} -->
<!-- imports_data[renglones_problema, columnas_problema] -->
<!-- ``` -->

<!-- Aparentemente existen dos tipos de problemas: -->

<!-- * En algunos renglones `curb_weight` estaba pegado con `engine_type` -->
<!-- * En el rengón 157 el formato de `wheel_base` es muy extraño -->

<!-- Estos problemas se eliminan en el script `02-clean.R`. -->

<!-- ```{r engine='bash', comment=''} -->
<!-- cat 02-clean.R -->
<!-- ``` -->

<!-- ```{r} -->
<!-- source('02-clean.R') -->
<!-- ``` -->

<!-- Verificamos que ya no haya errores en los renglones y columnas problema. -->

<!-- ```{r} -->
<!-- imports_data[renglones_problema, columnas_problema] -->
<!-- ``` -->

<!-- # Ejercicio 2 -->

<!-- El propósito de este ejercicio es realizar un análisis exploratorio sobre los datos. -->

<!-- Primero exploramos con `summary` cada variable para conocer un poco más el contenido de cada columna. -->

<!-- ```{r} -->
<!-- lapply(imports_data, summary) -->
<!-- ``` -->

<!-- Realizamos un análisis univariado inicial con el script `03-eda.R` que recorre todas las variables. -->

<!-- ```{r engine='bash', comment=''} -->
<!-- cat 03-eda.R -->
<!-- ``` -->

<!-- ```{r} -->
<!-- source('03-eda.R') -->
<!-- ``` -->

<!-- ## Análisis Univariado -->

<!-- Veamos a detalle 10 variables seleccionadas: -->

<!-- categóricas: -->

<!-- * `make` -->
<!-- * `fuel_type` -->
<!-- * `body_style` -->
<!-- * `num_of_cylinders` -->
<!-- * `num_of_doors` -->

<!-- cuatitativas: -->

<!-- * `lenght` -->
<!-- * `width` -->
<!-- * `height` -->
<!-- * `horsepower` -->
<!-- * `price` -->

<!-- Adicionalmete, al explorar `curb_weight`, se observan datos atípicos que se separan demasiado de los demás valores de `curb_weight`. -->

<!-- ### make -->

<!-- La marca con más carros en este estudio es **toyota**. -->

<!-- ```{r} -->
<!-- ggplot(imports, aes(make, fill = make)) + -->
<!--   geom_bar(colour = 'grey', alpha = 0.7) +  -->
<!--   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + -->
<!--   labs(title = "numero de carros por marca", x = "make", y = "count") + -->
<!--   coord_flip() -->
<!-- ``` -->

<!-- Observamos que hay **mercedes-bens** y **mercedes-benz**. Esto no lo habíamos corregido antes pero se corrige ahora. -->
<!-- ```{r} -->
<!-- imports$make <- gsub("mercedes-bens", "mercedes-benz", imports$make) -->
<!-- ``` -->

<!-- ### fuel_type -->

<!-- Hay muchos más carros **diesel** que **gas**. -->

<!-- ```{r} -->
<!-- ggplot(imports, aes(fuel_type, fill = fuel_type)) + -->
<!--   geom_bar(colour = 'grey', alpha = 0.7) +  -->
<!--   theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + -->
<!--   labs(title = "numero de carros por tipo de combustible", x = "fuel type", y = "count") -->
<!-- ``` -->

<!-- ### body_style -->

<!-- **Sedan** y **hatchback** son los estilos de carros más comunes. -->

<!-- ```{r} -->
<!-- ggplot(imports, aes(body_style)) + -->
<!--   geom_bar(fill = 'orchid', colour = 'grey', alpha = 0.5) + -->
<!--   labs(title = "numero de carros por estilo", x = "body style", y = "count") -->
<!-- ``` -->

<!-- ### num_of_cylinders -->

<!-- Casi todos los carros son de cuatro **four** cilindros. -->

<!-- ```{r} -->
<!-- ggplot(imports, aes(x = 'num of cylinders', fill = num_of_cylinders)) +  -->
<!--   geom_bar(position = position_stack(), colour = 'grey', alpha = 0.7, width = .5) + -->
<!--   labs(title = "numero de carros por su numero de cilindros", x = "", y = "") -->
<!-- ``` -->

<!-- ### num_of_doors -->

<!-- Hay un poco más carros de cuatro **four** puertas que de dos **two**. -->

<!-- ```{r} -->
<!-- ggplot(imports, aes(x = 'num of doors', fill = num_of_doors)) +  -->
<!--   geom_bar(position = position_stack(), colour = 'grey', alpha = 0.7, width = .5) + -->
<!--   labs(title = "numero de carros por su numero de puertas", x = "", y = "") -->
<!-- ``` -->


<!-- ### length -->

<!-- La longitud `length` puede considerarse una distribución simétrica. -->

<!-- ```{r, warning=FALSE} -->
<!-- p1 <-ggplot(imports, aes(x = length, y=..density..)) + -->
<!--   geom_histogram(binwidth = 8) + -->
<!--   geom_density(bw = 4, colour = "blue", fill = "blue", alpha = 0.08) + -->
<!--   ggtitle("distribucion de length") -->

<!-- p2 <- ggplot(imports, aes(x = "length", y = length)) + -->
<!--   geom_boxplot() + geom_jitter() -->

<!-- grid.arrange(p1, p2, ncol=2) -->
<!-- ``` -->

<!-- Contemos los **datos atípicos**. -->

<!-- ```{r} -->
<!-- summ <- summary(imports$length) -->
<!-- SD <- sd(imports$length) -->
<!-- IQR <- summ[['3rd Qu.']] - summ[['1st Qu.']] -->

<!-- outliers_symetric <- which(imports$length > summ[['Mean']] + SD | imports$length < summ[['Mean']] - SD) -->
<!-- paste('numero de datos atipicos:', length(outliers_symetric)) -->
<!-- ``` -->

<!-- ### width -->

<!-- El ancho `width` puede considerarse una distribución simétrica. -->

<!-- ```{r, warning=FALSE} -->
<!-- p1 <- ggplot(imports, aes(x = width, y=..density..)) + -->
<!--   geom_histogram(binwidth = 2) + -->
<!--   geom_density(bw = 1, colour = "purple", fill = "purple", alpha = 0.08) + -->
<!--   ggtitle("distribucion de width") -->

<!-- p2 <- ggplot(imports, aes(x = "width", y = width)) + -->
<!--   geom_boxplot() + geom_jitter() -->

<!-- grid.arrange(p1, p2, ncol=2) -->
<!-- ``` -->

<!-- Contemos los **datos atípicos**. -->

<!-- ```{r} -->
<!-- summ <- summary(imports$width) -->
<!-- SD <- sd(imports$width) -->
<!-- IQR <- summ[['3rd Qu.']] - summ[['1st Qu.']] -->

<!-- outliers_symetric <- which(imports$width > summ[['Mean']] + SD | imports$width < summ[['Mean']] - SD) -->
<!-- paste('numero de datos atipicos:', length(outliers_symetric)) -->
<!-- ``` -->

<!-- ### height -->

<!-- La altura `height` puede considerarse una distribución simétrica. -->

<!-- ```{r, warning=FALSE} -->
<!-- p1 <- ggplot(imports, aes(x = height, y=..density..)) + -->
<!--   geom_histogram(binwidth = 2) + -->
<!--   geom_density(bw = 1, colour = "red", fill = "red", alpha = 0.08) + -->
<!--   ggtitle("distribucion de height") -->

<!-- p2 <- ggplot(imports, aes(x = "height", y = height)) + -->
<!--   geom_boxplot() + geom_jitter() -->

<!-- grid.arrange(p1, p2, ncol=2) -->
<!-- ``` -->

<!-- Contemos los **datos atípicos**. -->

<!-- ```{r} -->
<!-- summ <- summary(imports$height) -->
<!-- SD <- sd(imports$height) -->
<!-- IQR <- summ[['3rd Qu.']] - summ[['1st Qu.']] -->

<!-- outliers_symetric <- which(imports$height > summ[['Mean']] + SD | imports$height < summ[['Mean']] - SD) -->
<!-- paste('numero de datos atipicos:', length(outliers_symetric)) -->
<!-- ``` -->

<!-- ### horsepower -->

<!-- Los caballos de fuerza `horsepower` tiene una distribución asimétrica con sesgo a la izquierda. -->

<!-- ```{r, warning=FALSE} -->
<!-- p1 <- ggplot(imports, aes(x = horsepower, y=..density..)) + -->
<!--   geom_histogram(binwidth = 30) + -->
<!--   geom_density(bw = 15, colour = "brown", fill = "brown", alpha = 0.08) + -->
<!--   ggtitle("distribucion de horsepower") -->

<!-- p2 <- ggplot(imports, aes(x = "horsepower", y = horsepower)) + -->
<!--   geom_boxplot() + geom_jitter() -->

<!-- grid.arrange(p1, p2, ncol=2) -->
<!-- ``` -->

<!-- Contemos los **datos atípicos**. -->

<!-- ```{r} -->
<!-- summ <- summary(imports$horsepower) -->
<!-- SD <- sd(imports$horsepower) -->
<!-- IQR <- summ[['3rd Qu.']] - summ[['1st Qu.']] -->

<!-- outliers_assymetric <- which(imports$horsepower > summ[['3rd Qu.']] + 1.5 * IQR | imports$horsepower < summ[['1st Qu.']] - 1.5 * IQR ) -->
<!-- paste('numero de datos atipicos:', length(outliers_assymetric)) -->
<!-- ```  -->

<!-- ### price -->

<!-- El precio `price` tiene una distribución asimétrica con sesgo a la izquierda. -->

<!-- ```{r, warning=FALSE} -->

<!-- p1 <- ggplot(imports, aes(x = price, y=..density..)) + -->
<!--   geom_histogram(binwidth = 3000) + -->
<!--   geom_density(bw = 2000, colour = "green", fill = "green", alpha = 0.08) + -->
<!--   ggtitle("distribucion de price") -->

<!-- p2 <- ggplot(imports, aes(x = "price", y = price)) + -->
<!--   geom_boxplot() + geom_jitter() -->

<!-- grid.arrange(p1, p2, ncol=2) -->
<!-- ``` -->

<!-- Contemos los **datos atípicos**. -->

<!-- ```{r} -->
<!-- summ <- summary(imports$price) -->
<!-- SD <- sd(imports$price) -->
<!-- IQR <- summ[['3rd Qu.']] - summ[['1st Qu.']] -->

<!-- outliers_assymetric <- which(imports$price > summ[['3rd Qu.']] + 1.5 * IQR | imports$price < summ[['1st Qu.']] - 1.5 * IQR ) -->
<!-- paste('numero de datos atipicos:', length(outliers_assymetric)) -->
<!-- ```  -->

<!-- ### curb_weight -->

<!-- En particular se corregirá la variable `curb_weight` parece tener errores de captura -->

<!-- ```{r, warning=FALSE} -->
<!-- p1 <- ggplot(imports, aes(x = curb_weight, y=..density..)) + -->
<!--   geom_histogram(binwidth = 3000) + -->
<!--   geom_density(bw = 2000, colour = "green", fill = "green", alpha = 0.08) + -->
<!--   ggtitle("distribucion de price") -->

<!-- p2 <- ggplot(imports, aes(x = "curb weight", y = curb_weight)) + -->
<!--   geom_boxplot() + geom_jitter() -->

<!-- grid.arrange(p1, p2, ncol=2) -->
<!-- ``` -->

<!-- Contemos los **datos atípicos**. -->

<!-- ```{r} -->
<!-- summ <- summary(imports$curb_weight) -->
<!-- SD <- sd(imports$curb_weight) -->
<!-- IQR <- summ[['3rd Qu.']] - summ[['1st Qu.']] -->

<!-- outliers_assymetric <- which(imports$curb_weight > summ[['3rd Qu.']] + 1.5 * IQR | imports$curb_weight < summ[['1st Qu.']] - 1.5 * IQR ) -->
<!-- paste('numero de datos atipicos:', length(outliers_assymetric)) -->
<!-- ```  -->

<!-- Eliminaremos los datos atipicos para volver a graficar los datos de `curb_weight`. -->

<!-- ```{r, warning=FALSE} -->
<!-- p1 <- ggplot(imports[-outliers_assymetric, ], aes(x = curb_weight, y=..density..)) + -->
<!--   geom_histogram(binwidth = 500) + -->
<!--   geom_density(bw = 500, colour = "green", fill = "green", alpha = 0.08) + -->
<!--   ggtitle("distribucion de price") -->

<!-- p2 <- ggplot(imports[-outliers_assymetric, ], aes(x = "curb weight", y = curb_weight)) + -->
<!--   geom_boxplot() + geom_jitter() -->

<!-- grid.arrange(p1, p2, ncol=2) -->
<!-- ``` -->

<!-- ## Análisis bivariado -->

<!-- ### price vs make -->

<!-- Como podíamos esperar **jaguar** es de las marcas más caras y **chevrolet** de las más baratas. -->

<!-- ```{r, warning=FALSE} -->
<!-- pltdata <- imports %>% -->
<!--   select(make, price) %>% -->
<!--   group_by(make) %>% -->
<!--   summarize(price = mean(price, na.rm = TRUE)) %>% -->
<!--   arrange(price) %>% -->
<!--   mutate(make = ordered(make, levels = make)) -->

<!-- ggplot(pltdata, aes(x = make, y = price)) + -->
<!--   geom_bar(stat = "identity") + -->
<!--   theme(axis.text.x = element_text(angle = 45, hjust = 1)) + -->
<!--   ggtitle("Mean price vs make") -->

<!-- ``` -->

<!-- ### price vs fuel_type -->

<!-- Los vehículos de **diesel** son más caros que los de **gas**. -->

<!-- ```{r, warning=FALSE} -->
<!-- pltdata <- imports %>% -->
<!--   select(fuel_type, price) -->

<!-- ggplot(pltdata, aes(x = fuel_type, y = price)) + -->
<!--   geom_boxplot() + -->
<!--   ggtitle("Fuel type vs price") -->

<!-- ``` -->

<!-- ### price vs body_style -->

<!-- Aunque los **convertible** son en general más caros que los **sedan**, existen algunos **sedan** igualmente caros. -->

<!-- ```{r, warning=FALSE} -->
<!-- pltdata <- imports %>% -->
<!--   select(body_style, price) -->

<!-- ggplot(pltdata, aes(x = body_style, y = price)) + -->
<!--   geom_boxplot() + -->
<!--   ggtitle("Body type vs price") -->

<!-- ``` -->

<!-- ### price vs num_of_cylinders -->

<!-- Casi no existen vehículos con dos **two** o doce **twelve** cilindros por lo que se puede decir poco de su precio. Sin embargo, en general, más cilindros `num_of_cylinders` implica más precio `price`. -->

<!-- ```{r, warning=FALSE} -->
<!-- pltdata <- imports %>% -->
<!--   select(num_of_cylinders, price) %>% -->
<!--   mutate(num_of_cylinders = ordered(num_of_cylinders, -->
<!--                                     levels = c("two", "three", "four", "five", "six", "eight", "twelve"))) -->

<!-- ggplot(pltdata, aes(x = num_of_cylinders, y = price)) + -->
<!--   geom_boxplot() + -->
<!--   geom_jitter() + -->
<!--   ggtitle("num_of_cylinders vs price") -->
<!-- ``` -->

<!-- ### price vs num_of_doors -->

<!-- El número de puertas `num_of_doors` influye poco en el precio. -->

<!-- ```{r, warning=FALSE} -->
<!-- pltdata <- imports %>% -->
<!--   select(num_of_doors, price) %>% -->
<!--   mutate(num_of_doors = ordered(num_of_doors, levels = c("two", "four"))) %>% -->
<!--   na.omit() -->

<!-- ggplot(pltdata, aes(x = num_of_doors, y = price)) + -->
<!--   geom_boxplot() + -->
<!--   ggtitle("num_of_doors vs price") -->

<!-- ``` -->

<!-- ### price vs variables continuas -->

<!-- En las siguientes gráficas podemos observar: -->

<!-- * `price` vs `width` y `length` - la relación entre `price` vs `width` y `length` es en general estrictamente creciente. -->
<!-- * `price` vs `height` - la relación entre `price` y `height` tiene un comportamiento interesante. En general mientras más altos sean los vehículos más caros son. Sin embargo, existen 1) carros muy chaparros que No son tan baratos y 2) carros muy altos que son baratos. Esto tiene sentido si pensamos en autos de carreras para el caso 1) y en camiones para el caso 2). -->
<!-- * `price` vs `horsepower` - la relación entre `price`y `horsepower` es positiva y crece rápidamente. -->

<!-- ```{r, warning=FALSE} -->
<!-- pltdata <- imports %>% -->
<!--   select(price, length, width, height, horsepower) %>% -->
<!--   na.omit() -->
<!-- plength <- ggplot(pltdata, aes(length, price)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess") + -->
<!--   xlab("") + ylab("")+ ggtitle("price vs length") -->
<!-- pwidth <- ggplot(pltdata, aes(width, price)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess") + -->
<!--   xlab("") + ylab("")+ ggtitle("price vs width") -->
<!-- pheight <- ggplot(pltdata, aes(height, price)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess") + -->
<!--   xlab("") + ylab("")+ ggtitle("price vs height") -->
<!-- phorsepower <- ggplot(pltdata, aes(horsepower, price)) + -->
<!--   geom_point() + -->
<!--   geom_smooth(method = "loess") + -->
<!--   xlab("") + ylab("")+ ggtitle("price vs horsepower") -->
<!-- gridExtra::grid.arrange(plength, pwidth, pheight, phorsepower, ncol = 2) -->
<!-- ``` -->

<!-- # Conclusiones -->

<!-- El análisis exploratorio de los datos en 'imports-85.csv' confirma aquello que por lo general se sabe de los vehículos. Aquí se incluye cada uno de los resultados que se obtuvieron arriba: -->

<!-- * La marca con más carros en este estudio es **toyota**. -->
<!-- * Hay muchos más carros **diesel** que **gas**. -->
<!-- * **Sedan** y **hatchback** son los estilos de carros más comunes. -->
<!-- * Casi todos los carros son de cuatro **four** cilindros. -->
<!-- * Hay un poco más carros de cuatro **four** puertas que de dos **two**. -->
<!-- * La longitud `length` puede considerarse una distribución simétrica. -->
<!-- * El ancho `width` puede considerarse una distribución simétrica. -->
<!-- * La altura `height` puede considerarse una distribución simétrica. -->
<!-- * Los caballos de fuerza `horsepower` tiene una distribución asimétrica con sesgo a la derecha. -->
<!-- * El precio `price` tiene una distribución asimétrica con sesgo a la izquierda. -->
<!-- * Como podíamos esperar **jaguar** es de las marcas más caras y **chevrolet** de las más baratas. -->
<!-- * Los vehículos de **diesel** son más caros que los de **gas**. -->
<!-- * Aunque los **convertible** son en general más caros que los **sedan**, existen algunos **sedan** igualmente caros. -->
<!-- * Casi no existen vehículos con dos **two** o doce **twelve** cilindros por lo que se puede decir poco de su precio. Sin embargo, en general, más cilindros `num_of_cylinders` implica más precio `price`. -->
<!-- * El número de puertas `num_of_doors` influye poco en el precio. -->
<!-- * `price` vs `width` y `length` - la relación entre `price` vs `width` y `length` es en general estrictamente creciente. -->
<!-- * `price` vs `height` - la relación entre `price` y `height` tiene un comportamiento interesante. En general mientras más altos sean los vehículos más caros son. Sin embargo, existen 1) carros muy chaparros que No son tan baratos y 2) carros muy altos que son baratos. Esto tiene sentido si pensamos en autos de carreras para el caso 1) y en camiones para el caso 2). -->
<!-- * `price` vs `horsepower` - la relación entre `price`y `horsepower` es positiva y crece rápidamente. -->

<!-- Como vemos, <span style="color:red"> aquello que era cierto sobre los vehículos en los ochentas también es cierto hoy!!! </span> -->
